#!/usr/bin/env ruby
# ./check_port <host> <port>
#
#   Returns success if there is a TCP socket open.  Useful when checking
#     for service availability.  matt.a.feenstra@gmail.com

require 'socket'
require 'timeout'

raise "\n\tsyntax:\n\t\t#{$0}\t<host> <port>" unless (
  ARGV[0].is_a?(String) && (ARGV[1].to_i > 0) )

def is_port_open?(ip, port)
  begin
    Timeout::timeout(1) do
      begin
        s = TCPSocket.new(ip, port)
        s.close
        return true
      rescue Errno::ECONNREFUSED, Errno::EHOSTUNREACH
        return false
      end
    end
  rescue Timeout::Error
  end

  return false
end

print "#{ARGV[0].to_s}:#{ARGV[1].to_i} open? "
is_port_open?(ARGV[0].to_s, ARGV[1].to_i) ? (p true; exit 0) : (p false; exit 1)
